[Main]
RealAppId=2492040
FakeAppId=480
#Language=english
BuildId=0
InstallDir=
UnlockAllDLC=false

[Misc]
ExtraProtection=false
PhotonIntegration=false
EmulateTicket=false

[Interfaces]
Apps=true
User=true
Utils=true
Storage=true
UserStats=true
Friends=true
UGC=true
Inventory=true
AppTicket=true

[EOSAuthWrapper]
BasicProfile=true
FriendsList=true
Presence=true

[DLC]
3141980=SteamDB Unknown App 3141980
3141970=FATAL FURY CotW - DLC Costume "FATAL FURY 2: TERRY"

[Hashes]
0=cb0947696b90801b6dbc26d37dc49069c9ea91ec14d8309b61e717f87ac246a10e0455acf6d537d521955ef38cf6e5cc491730a012c2316b7fd9d6d8f54306ed
